### ISSUE TITLE
Metadata

### ISSUE THREAD

**Issue by darkshadow543** [MightyPirates/BedrockOres#22]
How do I use metadata blocks?  Some mods use metadata for ores.

**Comment by fnuecke** [comment]
If you look at the block in the world with debug info on (F3), to the right you'll see the name of the block and it's current property values. The properties are basically a human-readable form of the metadata of the block, so that's what you have to add to the state definition (see [the ThermalFoundation config](https://github.com/MightyPirates/BedrockOres/blob/master-MC1.11/src/main/resources/assets/bedrockores/config/thermalfoundation.json) as an example).
