### ISSUE TITLE
Ores allow mob spawns

### ISSUE THREAD

**Issue by Thiana** [MightyPirates/BedrockOres#29]
Unlike regular bedrock, Bedrock Ores appear to allow mobs to spawn on them at the appropriate light levels. I'm not sure if this is intended behavior? Thanks.

**Comment by fnuecke** [comment]
It is, it just forwards that check to the contained ore because I thought that'd be more logical.
Could be argued it's more bedrock though... got some arguments either way? Otherwise I could always make it a config option... though I'd kinda like to not let the config grow too big :P

**Comment by Thiana** [comment]
I prefer it being spawnable. It makes it more dangerous for the player to simply clear a large area at bedrock with a quarry type device then walk around to find the deposit they want.

That said, the opposing argument is that it's supposed to be bedrock which vanilla minecraft marks as unspawnable (which is why I brought it up).

**Comment by fnuecke** [comment]
The challenge aspect is also a good point, tbh for me it was just more of a "they look like ores, so they (mostly) behave like ores" decision (until exhausted and turning into bedrock proper).

I think I'll leave it as-is, at least for now, if not for any clear winning argument just because I prefer it that way, too :P
