### ISSUE TITLE
Config/Feature: Biome specific bedrock ores

### ISSUE THREAD

**Issue by BBoldt** [MightyPirates/BedrockOres#31]
Would be nice to limit certain types of bedrock ores to certain biome types.

In addition to certain mods doing this, a good example is emerald in vanilla.

**Comment by fnuecke** [comment]
6254c3323a46765da4af869633623a0954bc86c7

Took that as an incentive to make the ore gen config JSONs a good bit more flexible: they can now do both dimension and biome constraints. Dimensions can be specified either by id or more generically their type (`0` vs. `overworld`), biomes via their registry name or more generically their type (`abyssalcraft:darklands` vs. `warm`). And they can alternatively be set to be interpreted as a blacklist instead of a whitelist. See [example JSON](https://github.com/MightyPirates/BedrockOres/blob/master-MC1.11/src/main/resources/assets/bedrockores/config/_example.json) for the format. Using that for emeralds now and also for #32!
