### ISSUE TITLE
Config/Feature: Mod support priority selecting

### ISSUE THREAD

**Issue by BBoldt** [MightyPirates/BedrockOres#33]
Let's consider I would like Immersive Engineering ores to generate in the world instead of Thermal Expansion ores. I can't figure out how to easily enable the IE support instead of the TE support.

In the mod description I noticed this:

> Note that the bedrock vein config allows grouping blocks. From each group, only the entry with the lowest sort order will actually be used. So e.g. if you have both TF and IC2 installed, it will automatically only generate TF copper in bedrock veins by default, and no IC2 copper. This makes the default config usable in most cases with just a few tweaks.

I have no way of viewing the default grouping sort order for the already supported mods, but it looks like I should be able to do it using the configuration options already provided.

Still, I would like to suggest an easier way to disable/enable the native support for specific mods, or easily adjust the priority for all the blocks in the mod at once instead of on an ore by ore basis.

**Comment by fnuecke** [comment]
b2975bf618005415c2606798df48586e7f3693d9, 8967ce9aaf7bf82da933774932d91cfd1b45e563

For the historical records, let it be said that you could look them up [in their respective default JSON here](https://github.com/MightyPirates/BedrockOres/tree/master-MC1.11/src/main/resources/assets/bedrockores/config), e.g. [for Immersive Engineering](https://github.com/MightyPirates/BedrockOres/blob/4ca67ea412f602484e9915171a2a9c945e4bedfb/src/main/resources/assets/bedrockores/config/immersiveengineering.json) you'd see it was set to 10.

But yeah, this was added early on when I didn't really anticipate there to be *that* many repeated ores :P I mean, I knew there were some, but... oh well. Anyway. Yes, as it stood this system would have required a lot of JSON config overrides to change the order (e.g. disable each of the entries that took precedence).

So, new system: in the config there's now a list of ore group priorities. In the [new Immersive Engineering JSON](https://github.com/MightyPirates/BedrockOres/blob/master-MC1.11/src/main/resources/assets/bedrockores/config/immersiveengineering.json) you'll see it now reads `"immersiveengineering"` instead of `10`. If a `groupOrder` is a string now, the index of that string in the [`orePriority` config](https://github.com/MightyPirates/BedrockOres/blob/master-MC1.11/src/main/java/li/cil/bedrockores/common/config/Settings.java#L73-L81) is looked up, and that index is multiplied by 5 to get the sort order. So to prefer Forestry ores over IC2 ores, for example, you'd just have to move the `forestry` string in the `orePriority` config list to above the `ic2` one in your `bedrockore.cfg`.

Also added a config to disable all blocks from individual mods for convenience, `oreModBlacklist`. This is a list of *mod IDs*, for which no block will be spawned as an ore. So e.g. to disable Thermal Foundation ores, put `thermalfoundation` in it.

**Comment by BBoldt** [comment]
Fantastic! This is exactly what I was looking for. Thanks for your help.
