### ISSUE TITLE
Issues with using types

### ISSUE THREAD

**Issue by megaloloful** [MightyPirates/BedrockOres#4]
I've tried to convert the default json to use geolosys ores, but the mod somehow doesn't read the types properly

the json: https://pastebin.com/PpDgnhv4
Screenshot of the list command output: http://imgur.com/a/qcHJw

minecraft 1.12
Bedrock Ores-MC1.12-1.0.0.6.jar

**Comment by fnuecke** [comment]
Pretty sure that's because it should be "variant" not "type" as the property name: see the right bottom line in the debug overlay where it says "variant: azurite"? That's what needs to go into the JSON. You should also have a couple of warnings in the logs.

![2017-08-25_02 52 00](https://user-images.githubusercontent.com/514903/29695040-7d57a938-8940-11e7-8799-214db6d9e4a0.png)


I suppose it might make more sense to just drop entries where property parsing failed, and add a command to list the ones that errored. I'll look into that tomorrow.
