### ISSUE TITLE
Option to increase Ore's Harvest Level

### ISSUE THREAD

**Issue by nmarshall23** [MightyPirates/BedrockOres#40]
I would like Bedrock Ores to be slightly harder to get then the normal version of that ore.

My feature request is for two new config options to set the Harvest Level of common ores and rare ores. These options wouldn't change the Ore Miner's ability to harvest bedrock ores. 

This would let me set Iron Bedrock Ore to require a Diamond Pickaxe. I could also set the Diamond Ore to require a Pickaxe of Tinker's Cobalt.

**Comment by fnuecke** [comment]
I'm afraid this isn't possible without some massive reworking of how things work under the hood. Right now, I'm just returning the wrapped block state, and most these checks simply happen on that. The beauty of that is that there's virtually no need for special cases and that things "just work" with pretty much any ore.

I don't really want to start generating "fake" block states to add a layer between the actual block states and whoever uses them to do checks (e.g. player for harvesting), because I fear this would invite a lot of subtle and annoying bugs. Sorry.
