### ISSUE TITLE
Default ore weight?

### ISSUE THREAD

**Issue by esotericist** [MightyPirates/BedrockOres#41]
I cannot for the life of me figure out what the default weight is if unspecified. The _example.json doesn't mention this, so I don't know what to use for weights relative other materials, for instance the vanilla ores. Only Emerald has a weight specified.

Of the other mod ores, only some are specified, so I can infer that for instance 5 is lower than the default, but I still cannot determine what the default is even looking at the source code.

This really should be explicit somewhere.

**Comment by esotericist** [comment]
Looking closer at _example.json, I notice this line:
`    "field_76292_a": 10`

... Is that supposed to be 'weight'? Half-hearted searching seems to suggest that's the identifier used in some vanilla weighted random code.

**Comment by esotericist** [comment]
While I'm here, there also seems to be 'heightMin' and 'heightMax' values in the example without any explanation, so I think the _example.json needs some attention in general.

**Comment by fnuecke** [comment]
Oh ffs, obfuscation leading to JSON serialization writing out that instead of `"weight" : 10`. Will fix that.

And the height* settings were missing documentation indeed, will add that. Everything else should be fully and correctly documented.

Edit: gah, also some stuff getting removed, I could've sworn that was a straight copy-file. Will fix that, too.

**Comment by esotericist** [comment]
You have my sympathies.

**Comment by esotericist** [comment]
So, am I correct to conclude that the default weight is in fact 10? Might be good to specify that in the document for clarity.
