### ISSUE TITLE
[feature request] config to adjust hardness and amount separately

### ISSUE THREAD

**Issue by Zygus42** [MightyPirates/BedrockOres#5]
I would like to be able to adjust the mining hardness and the quantity amount separately, so that I can make it hard to mine, but have less resources in the blocks.

**Comment by fnuecke** [comment]
Hmm, not sure what you mean. The hardness is just the hardness of the contained ore: harvestability and hardness checks are forwarded to the contained ore block, and I don't want to change that.

Unless mean the time it takes the automatic miner to extract a single ore? (Because that's the same regardless of ore right now.)

**Comment by Zygus42** [comment]
I was under the impression that the ore got harder to mine the further it was from spawn, but on rereading it, it seems it just gets bigger.
