### ISSUE TITLE
Suggestion: Vein size scale option in config

### ISSUE THREAD

**Issue by Ithronyar** [MightyPirates/BedrockOres#57]
Simple suggestion. A new config value that universally scales the physical size of all bedrock ore veins generated, regardless of their distance from spawn. This wouldn't affect their yield, just the number of blocks each vein contains. For example, a size scale of 100x would produce a huge clump of bedrock ores per vein, but each block would have a normal yield.

**Comment by fnuecke** [comment]
You can control the scaling of veins in the ore configs (see [the example one for the properties](https://github.com/MightyPirates/BedrockOres/blob/master-MC1.11/src/main/resources/assets/bedrockores/config/_example.json#L107-L108)), but i'm afraid the size is hard capped to 15 because I couldn't get the distribution of ores I wanted with larger ones without running into cascading generation issues (i.e. chunks starting to generate ad infinitum because more chunk gen got triggered during generation).
