### ISSUE TITLE
Texture for bedrock ore mask is sometimes flipped

### ISSUE THREAD

**Issue by StarkRG** [MightyPirates/BedrockOres#58]
I'm trying to make a soartex texture for this mod, but it appears that about half the time the overlay texture is flipped but the underlying ore texture is not.

[See here for an example](https://imgur.com/a/JioOy).

**Comment by fnuecke** [comment]
Hm, I'm guessing that's because the underlying ore block state doesn't have mirrored variants. You should be able to fix this by overriding [the Bedrock Ore mask block state](https://github.com/MightyPirates/BedrockOres/blob/master-MC1.11/src/main/resources/assets/bedrockores/blockstates/bedrock_ore_mask.json) in your resource pack with one that just doesn't contain the mirrored entries.
