### ISSUE TITLE
Syntax help request

### ISSUE THREAD

**Issue by 666lumberjack** [MightyPirates/BedrockOres#62]
Hi, I'm trying to set up Bedrock Ore veins for Iron, Lead, Copper, Tin, Nickel and Uranium, and disable all others. I've been able to turn off most mods' ores by adding them to the oreModBlacklist in the main config, but the json files I've created in an attempt to disable vanilla ores aren't working. I'm assuming I'm just making an error somewhere in the syntax, but I'm not sure what exactly it is. 

I have created pastebins of the two files below:

https://pastebin.com/J1xCb7uK
https://pastebin.com/Y72t7frk

**Comment by rioninnimo** [comment]
1)
"name": "<nuclearcraft:ore",
      "properties": {
        "type": "tin"
      }

Are you sure <nuclearcraft:ore is proper name ? Maybe without < it will be better ?
 And files in your minecraft/config/bedrockores directory have .json extension and NOT like in pastebin .json.txt , right ?

2)
{
    "enabled": true,
    "state": {
      "name": "minecraft:lapis_ore",
    },
    "weight": 0
  }

Well ,i dont see why it wont disable lapis ore, but since it not working - maybe use 
"enabled": false
 instead of 
"enabled": true
 Maybe it will disable it finally.

**Comment by rioninnimo** [comment]
Oh , waaaaait . This -
 {"name": "minecraft:lapis_ore",}
  The , before } Yeah. That pesky commas. Happened to me too. If {} border one thing , not several , comma have no place there and it ruins everything.

**Comment by fnuecke** [comment]
Yeah, pretty sure those commas are it, at least in part. Should have also popped up in the logs :)
