### ISSUE TITLE
Bedrock ores spawning in bedrock above the initial layer

### ISSUE THREAD

**Issue by Tellik** [MightyPirates/BedrockOres#64]
I'm trying to get Bedrock Ores and Hardcore Spelunking working together. 

Hardcore Spelunking (https://www.curseforge.com/minecraft/mc-mods/hardcore-spelunking) basically generates bedrock (or an filler block that you specify) replacing stone in world generation.

I've tried playing around with the weights, to get one to generate before the other, swapping the order that Bedrock Ores or Hardcore Spelunking generate with no change. Bedrock Ores spawns only in the initial bottom layers of bedrock. I did change the number of bedrock layers at the bottom, using COFH world, and bedrock ores spawned in all 8 layers, but ignored the upper layers above that.

Is there something I'm missing or is this not a possible interaction.

**Comment by fnuecke** [comment]
Have a look at the `veinBaseY` config. But just so you're aware of this, bedrock ore generation is technically just 2D, i.e. it'll still just generate patches on the plane, but if you raise that they'll span from bottom to top, which may not be what you want. Why is it this way? Because usually bedrock is only at the bottom, and this is a lot more predictable and efficient this way.
